spring:
  application:
    name: order-service
  profiles:
    active: default
  cloud:
    config:
      override-none: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka


feign:
  hystrix:
    enabled: true
---
spring:
  profiles: default

server:
  port: 8201

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
---
spring:
  profiles: backup

server:
  port: 8202

management:
  endpoints:
    web:
      exposure:
        include: "*"
